config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get 'help'      =>  'static_pages#help'
  get 'about'     =>  'static_pages#about'
  get 'contact'   =>  'static_pages#contact'
  get 'signup'    =>  'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :sighting_records,    only: [:create, :destroy]
  resources :messages,            only: [:new, :create]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @sighting_record = current_user.sighting_records.build 
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_new_user.html.erb
<div class="center jumbotron">

  <h1>Birder's Life List</h1>

  <h2>
      This is the home page for the Birder's Life List application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/_signed_in_user.html.erb
<div class="row">
  <aside class="col-md-6">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/sighting_record_form' %>
    </section>
  </aside>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the about page for the Birder's Life List application.</br>
  The orders and families are those listed in the IOC Master List, v5.3, <%= link_to 'http://www.worldbirdnames.org/ioc-lists/master-list-2/' %>, last accessed 17-9-2015.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact us</h1>
<p>
  Click the link below to send a message to Paleograph Web Services.
</p>
<li><%= link_to "Send message",   new_message_path %></li>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This is the help page for the Birder's Life List application.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'static_pages/signed_in_user' %>
<% else %>
  <%= render 'static_pages/new_user' %>
<% end %>